---

- hosts: all
  remote_user: root
  force_handlers: yes
  roles:
    - jasmin.awx
  tasks:
    - name: Ensure Tower API is available
      command: tower-cli version
      register: tower_cli_version
      until: tower_cli_version is succeeded
      retries: 120
      delay: 5

    - name: Create Cluster-as-a-Service organisation
      tower_organization:
        name: "Cluster-as-a-Service"
        tower_verify_ssl: no

    - name: Install Cluster-as-a-Service projects
      tower_project:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        scm_type: git
        scm_url: "{{ item.git_url }}"
        state: present
        tower_verify_ssl: no
      with_items:
        - name: Kubernetes
          description: "Playbooks for installing and maintaining Kubernetes clusters"
          git_url: https://github.com/cedadev/k8s-ansible.git
