---

- name: "Create project: {{ cluster_type.name }}"
  tower_project:
    organization: "Cluster-as-a-Service"
    name: "{{ cluster_type.name }}"
    description: "{{ cluster_type.description }}"
    scm_type: git
    scm_url: "{{ cluster_type.git_url }}"
    # Each time a job runs using this project, make sure the
    # playbook is at the latest version
    scm_update_on_launch: yes
    tower_verify_ssl: no
  register: tower_project

- name: "Wait for project to become available: {{ cluster_type.name }}"
  shell: |
    set -eo pipefail
    tower-cli project status -f json {{ tower_project.id }} | \
      jq -e '.status == "successful"'
  register: tower_project_available
  until: tower_project_available is succeeded
  retries: 60
  delay: 5

# The tower_job_template module doesn't permit the setting of the instance group,
# cloud credential or survey, so use the tower-cli directly for those
# after initial creation
- name: "Create job template: {{ cluster_type.name }}"
  tower_job_template:
    name: "{{ cluster_type.name }}"
    job_type: run
    project: "{{ cluster_type.name }}"
    playbook: "{{ cluster_type.playbook }}"
    # Ask for the inventory
    ask_inventory: yes
    tower_verify_ssl: no

- name: "Associate deploy user credential: {{ cluster_type.name }}"
  command: >
    tower-cli job_template associate_credential
      --job-template={{ cluster_type.name | quote }}
      --credential="Deploy User"

# We are treating instance groups like queues - fixing the instance group
# for Cluster-as-a-Service jobs allows us to suspend them in order to
# perform maintenance on the AWX host itself using a dedicated instance
# group that points to the same host
- name: "Associate tower instance group: {{ cluster_type.name }}"
  command: >
    tower-cli job_template associate_ig
      --job_template={{ cluster_type.name | quote }}
      --instance_group=tower

# The tower_job_template module also doesn't allow the setting of the survey spec,
# so use the tower-cli directly for that as well
- name: "Update job template survey: {{ cluster_type.name }}"
  command: >
    tower-cli job_template modify
      --name={{ cluster_type.name | quote }}
      --survey-enabled=true
      --survey-spec={{ {"name": "", "description": "", "spec": cluster_type.survey_spec} | to_json | quote }}

- name: "Create sample inventory: {{ cluster_type.name }}"
  tower_inventory:
    name: "{{ cluster_type.name }} Sample Inventory"
    organization: "Cluster-as-a-Service"
    description: "Sample inventory for a {{ cluster_type.name }} cluster. Copy and modify as required."
    variables: "{{ cluster_type.inventory_defaults }}"
    tower_verify_ssl: no

- name: "Add openstack host to sample inventory: {{ cluster_type.name }}"
  tower_host:
    name: openstack
    inventory: "{{ cluster_type.name }} Sample Inventory"
    variables:
      ansible_host: "127.0.0.1"
      ansible_connection: local
    tower_verify_ssl: no
