---

- name: "Create project: {{ job_template.name }}"
  tower_project:
    organization: "Cluster-as-a-Service"
    name: "{{ job_template.name }}"
    description: "{{ job_template.description }}"
    scm_type: git
    scm_url: "{{ job_template.git_url }}"
    state: present
    tower_verify_ssl: no

- name: "Create job template: {{ job_template.name }}"
  tower_job_template:
    name: "{{ job_template.name }}"
    job_type: run
    project: "{{ job_template.name }}"
    playbook: "{{ job_template.playbook }}"
    # Ask for OpenStack credential
    ask_credential: yes
    # Ask for the inventory
    ask_inventory: yes
    tower_verify_ssl: no
