---

- name: "Create project: {{ job_template.name }}"
  tower_project:
    organization: "Cluster-as-a-Service"
    name: "{{ job_template.name }}"
    description: "{{ job_template.description }}"
    scm_type: git
    scm_url: "{{ job_template.git_url }}"
    state: present
    tower_verify_ssl: no
  register: tower_project

- name: "Wait for project to become available: {{ job_template.name }}"
  shell: |
    set -eo pipefail
    tower-cli project status -f json {{ tower_project.id }} | \
      jq -e '.status == "successful"'
  register: tower_project_available
  until: tower_project_available is succeeded
  retries: 60
  delay: 5

- name: "Create job template: {{ job_template.name }}"
  tower_job_template:
    name: "{{ job_template.name }}"
    job_type: run
    project: "{{ job_template.name }}"
    playbook: "{{ job_template.playbook }}"
    # Ask for OpenStack credential
    ask_credential: yes
    # Ask for the inventory
    ask_inventory: yes
    tower_verify_ssl: no
  register: tower_job_template

- name: "Update job template survey: {{ job_template.name }}"
  command: >
    tower-cli job_template modify
      --survey-enabled=true
      --survey-spec={{ {"name": "", "description": "", "spec": job_template.survey_spec} | to_json | quote }}
      {{ tower_job_template.id }}
